Реквест
Andrewmer/yard-frontend pull request #2
Opened 2017-06-25 14:31 UTC by Andrewmer

Кажется, я с этими контейнерами много что напутал. В карточке белый фон сделал с помощью margin от img. И сделал его фиксированным (700px), а надо как-то автоматически. South Beach вниз улетел. И кстати, откуда взять фоновый паттерн?

2017-06-26 13:08 UTC, imevro requested changes

2017-06-26 13:08 UTC, evgenyrodionov commented on complex.html
> +  <header class="header clearfix">
что за клеарфикс

2017-06-26 13:08 UTC, evgenyrodionov commented on complex.html
> +    <img src="./compass-logo.svg" class="compass-logo">
почему отступы не как будто вложено в контейнер?

2017-06-26 13:08 UTC, evgenyrodionov commented on complex.html
> +	  <a class="layer" href="#">Купить</a>
поясни за название класса

2017-06-26 13:08 UTC, evgenyrodionov commented on complex.html
> +    <div class="black">
и опять

2017-06-26 13:08 UTC, evgenyrodionov commented on complex.html
> +  	  <h2 class="dscver">Discover Our New Development</h2>
экономия байтов?

2017-06-26 13:08 UTC, evgenyrodionov commented
флоаты запрещены
нейминг плохой
кодстайл плохой

2017-06-27 23:18 UTC, imevro requested changes
в целом стало лучше, но у тебя бардак с файлами

1) почему битмап.жпг и битмап.пнг? выбери одно
2) почему все файлы в корне? хтмл должны быть в корне, а остальные по images/ и styles/ директориям

2017-06-27 23:18 UTC, evgenyrodionov commented on style.css
> +
что за 15 пустых строк

2017-06-27 23:18 UTC, evgenyrodionov commented on style.css
> +.card-img {
ты этот класс не используешь

2017-06-28 14:10 UTC, imevro requested changes

2017-06-28 14:10 UTC, evgenyrodionov commented on complexes.html
> +	        <a class="header-link-end" href="#">Наши агенты</a>
а зачем этот постфикс энд

2017-06-28 14:10 UTC, evgenyrodionov commented on complexes.html
> +      <img src="img/bitmap.png" alt="100 East 53rd Street">
а кард-имг куда пропал

2017-06-28 14:10 UTC, evgenyrodionov commented on complexes.html
> +            <a class="footer-link margin" href="#">Все ЖК Москвы &#x2192;</a>
марджин слишком глобальный класс

2017-06-28 14:10 UTC, evgenyrodionov commented on complexes.html
> +            <a class="footer-link margin" href="#">Все ЖК Москвы &#x2192;</a>
и зачем вот этот х2192, там иконка свг сделана

2017-06-28 14:10 UTC, evgenyrodionov commented on complexes.html
> +          <div class="footer-rights">
зачем лишний див если класс можно повесить на р

2017-06-29 10:35 UTC, imevro requested changes

2017-06-29 10:35 UTC, evgenyrodionov commented on complexes.html
> +            <a class="footer-link footer-down" href="#">Все ЖК Москвы<img src="img/combined-shape.svg" class="footer-img"></a>
плохое название файла

2017-06-29 10:35 UTC, evgenyrodionov commented on complexes.html
> +          <p class="footer-info footer-down">+7 (999) 821-14-88</p>
не оч понятно что делает этот класс

2017-06-29 10:35 UTC, evgenyrodionov commented on style/style.css
> +.footer-img {
не оч понятно что это имеет отношение к иконке

2017-06-29 12:44 UTC, Andrewmer commented
Мерджить не надо. У меня бранч от develop с complex.html.

2017-06-29 13:14 UTC, imevro approved these changes

2017-07-02 23:01 UTC, merged

2017-07-02 23:01 UTC, evgenyrodionov commented
гит фетч --олл, гит чекаут мастер, гит пулл --ребейз