Create complex page
Andrewmer/yard-frontend pull request #3
Opened 2017-06-28 12:23 UTC by Andrewmer

2017-06-29 21:00 UTC, Andrewmer commented
Это мой предпоследний (если не последний коммит), так как с 30 июня по 2 июля меня не будет на связи. Управлюсь к утру с кнопкой, а остальное, надеюсь, в норме.

2017-06-29 21:04 UTC, Andrewmer commented
В gallery есть лишний класс для img, который не используется. Забыл удалить. Можно img без класса оставить вообще? А то я ничего с ними не делаю.

2017-06-29 21:23 UTC, evgenyrodionov commented
шрифты заголовков не той толщины

2017-06-29 21:24 UTC, imevro requested changes
кодстайл плохой нейминг плохой верстка не по макету

2017-06-29 21:24 UTC, evgenyrodionov commented on complex.html
> +	        <a class="header-link-end" href="#">Наши агенты</a>
есть же ласт чайлд селектор

2017-06-29 21:24 UTC, evgenyrodionov commented on complex.html
> +      <div class="row">
а зачем тут роу

2017-06-29 21:24 UTC, evgenyrodionov commented on complex.html
> +        <h1 class="complex-title">Жилой комплекс «Полянка/44»</h1>
что с отступами

2017-06-30 05:36 UTC, Andrewmer commented
Последний коммит. Не буду на связи до 2 июля.

2017-06-30 09:41 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27730318-75916e94-5d91-11e7-9666-2a7e99718b99.png)

2017-06-30 09:46 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/27730463-0171fb36-5d92-11e7-939f-370c6479a29c.png)

2017-07-02 23:00 UTC, imevro approved these changes

2017-07-02 23:00 UTC, merged