Convert pages into components with React
Andrewmer/yard-frontend pull request #4
Opened 2017-07-04 20:52 UTC by Andrewmer

2017-07-04 21:51 UTC, imevro requested changes
прикрути роутер и вторую страницу

2017-07-04 21:51 UTC, evgenyrodionov commented on public/index.html
> +    <title>React App</title>
камон

2017-07-05 21:42 UTC, imevro requested changes
читай чужие пры

2017-07-06 09:02 UTC, Andrewmer commented
Про react-flexboxgrid знаю, пока не использовал. Styled-components пока использовал только в двух компонентах. Интересует, что в остальном не так.

2017-07-06 09:51 UTC, imevro requested changes

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/List/Cards.js
> +        text="The Lewis Steel Building is a masterful industrial conversion located in
http://mxstbr.blog/2017/02/react-children-deepdive/

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/List/Discover.js
> +          <DiscoverInfo>
зачем эти префиксы если мы и так в дискавер

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/List/Discover.js
> +      <div className="row center-xs">
поставь преттир же

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/List/index.js
> +        <Cards />
читай чужие пры

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/ComplexName.js
> +import React from 'react';
это хедер, не нейм

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/ComplexName.js
> +import React from 'react';
вон у тебя кнопка "в избранное" лежит

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/Jakimanka.js
> +              <JakimankaCard
Якиманка это район в Москве

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/Offers.js
> +            key1="Площадь"
ужасно

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/Offers.js
> +            value1="от 59 до 120 м²"
читай чужие пры

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/OffersCard.js
> +            {props.key1}
если у тебя тут статик, то почему ты передаешь проп сверху?

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/OffersCard.js
> +          <small className="offers-card-key">
почему смолл

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/OffersCard.js
> +        <p className="offers-card-value">
почему параграф

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/OffersCard.js
> +          <small className="offers-card-key">
читай пр dt, dd, dl

2017-07-06 09:51 UTC, evgenyrodionov commented on src/Complexes/Show/Structure.js
> +            <div className="structure-item">Бассейн</div>
почему тут див?

2017-07-07 11:05 UTC, evgenyrodionov commented
Не нужно стайлед сюда, отдельным бранчем его сделай

2017-07-07 21:24 UTC, merged