Deploy Compass Project
Andrewmer/yard-frontend pull request #6
Opened 2017-07-11 20:52 UTC by Andrewmer

2017-07-11 20:52 UTC, Andrewmer commented
https://build-gwmardojnf.now.sh/complex

2017-07-11 21:52 UTC, imevro requested changes

2017-07-11 21:52 UTC, evgenyrodionov commented on package.json
> +    "eslint-plugin-jsx": "^0.0.2",
в девдепс

2017-07-11 21:52 UTC, evgenyrodionov commented on package.json
> +    "eslint-plugin-jsx": "^0.0.2",
хотя зачем вообще, что это за плагин

2017-07-11 21:52 UTC, evgenyrodionov commented on src/App.test.jsx
> +/* eslint-disable no-undef */
нет, энв настрой

2017-07-11 21:52 UTC, evgenyrodionov commented on src/App.test.jsx
> +/* eslint-disable no-undef */
в еслинтрс в смысле

2017-07-11 21:52 UTC, evgenyrodionov commented on src/index.js
> +/* eslint-disable no-undef */
нет

2017-07-12 12:40 UTC, imevro approved these changes

2017-07-12 12:40 UTC, merged